"""
Converts a PowerShell Format-Hex output (.txt) into a C source file
containing a uint32_t array.

PowerShell hex line format:
  00000000   48 65 6C 6C  6F 20 57 6F  72 6C 64 0D  0A          Hello Wo rld..

Usage:
  python hex_to_c_array.py <input.txt> <output.c> [array_name] [--bytes N] [--swap]

  array_name   optional, defaults to "data"
  --bytes N    only convert the first N bytes (default: all bytes)
  --swap       byte-swap each uint32_t (reverse the 4 bytes within every word)
               e.g. 0x7D8C0C39 becomes 0x390C8C7D
"""

import sys
import re
import os
import argparse


def parse_powershell_hex(filepath: str) -> bytes:
    """Read a PowerShell Format-Hex file and return the raw bytes."""
    hex_bytes: list[int] = []

    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            # Lines start with an 8-hex-digit offset followed by spaces/tabs
            # Example: "00000010   41 42 43 44  45 46 47 48  ..."
            m = re.match(r"^[0-9A-Fa-f]{8,16}[ \t]+(.+)", line)
            if not m:
                continue

            rest = m.group(1)

            # The ASCII preview at the end is separated by two or more spaces
            # after the last hex byte group — strip it by taking only tokens
            # that look like two-hex-digit byte values.
            tokens = rest.split()
            for token in tokens:
                if re.fullmatch(r"[0-9A-Fa-f]{2}", token):
                    hex_bytes.append(int(token, 16))
                else:
                    # First non-hex token marks the start of the ASCII column
                    break

    return bytes(hex_bytes)


def byteswap32(value: int) -> int:
    """Reverse the 4 bytes of a uint32_t value."""
    return (
        ((value & 0x000000FF) << 24) |
        ((value & 0x0000FF00) <<  8) |
        ((value & 0x00FF0000) >>  8) |
        ((value & 0xFF000000) >> 24)
    )


def bytes_to_uint32_array(data: bytes, swap: bool = False) -> list[int]:
    """
    Pack bytes into 32-bit unsigned integers (little-endian).
    If the byte count is not a multiple of 4, zero-pad to the right.
    If swap=True, byte-swap each word after packing.
    """
    # Pad to multiple of 4
    remainder = len(data) % 4
    if remainder:
        data = data + b"\x00" * (4 - remainder)

    values: list[int] = []
    for i in range(0, len(data), 4):
        word = int.from_bytes(data[i : i + 4], byteorder="little")
        if swap:
            word = byteswap32(word)
        values.append(word)

    return values


def write_c_array(values: list[int], array_name: str, out_path: str,
                  original_byte_count: int, swap: bool) -> None:
    """Write a C source file with a uint32_t array."""
    columns = 8  # hex values per line

    pad_note = (f" (padded {4 - original_byte_count % 4} byte(s) with 0x00)"
                if original_byte_count % 4 else "")
    swap_note = ", byte-swapped" if swap else ""

    lines = [
        "/* Auto-generated by hex_to_c_array.py */",
        "#include <stdint.h>",
        "",
        f"/* Original data size: {original_byte_count} bytes{pad_note}{swap_note} */",
        f"#define {array_name.upper()}_LEN {len(values)}",
        "",
        f"const uint32_t {array_name}[{len(values)}] = {{",
    ]

    for i in range(0, len(values), columns):
        chunk = values[i : i + columns]
        hex_vals = ", ".join(f"0x{v:08X}" for v in chunk)
        comma = "," if (i + columns) < len(values) else ""
        lines.append(f"    {hex_vals}{comma}")

    lines += ["};", ""]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert a PowerShell Format-Hex dump to a C uint32_t array."
    )
    parser.add_argument("input",      help="Path to the PowerShell hex dump (.txt)")
    parser.add_argument("output",     help="Path for the generated C file")
    parser.add_argument("array_name", nargs="?", default="data",
                        help="C array name (default: data)")
    parser.add_argument("--bytes", "-b", type=int, default=None, metavar="N",
                        help="Only convert the first N bytes (default: all)")
    parser.add_argument("--swap", "-s", action="store_true",
                        help="Byte-swap each uint32_t (flip endianness per word)")

    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"Error: '{args.input}' not found.")
        sys.exit(1)

    raw = parse_powershell_hex(args.input)
    if not raw:
        print("Error: no hex data found in the input file.")
        sys.exit(1)

    total_available = len(raw)

    if args.bytes is not None:
        if args.bytes <= 0:
            print("Error: --bytes must be a positive integer.")
            sys.exit(1)
        if args.bytes > total_available:
            print(f"Warning: --bytes {args.bytes} exceeds available data "
                  f"({total_available} bytes). Using all bytes.")
        else:
            raw = raw[:args.bytes]
            print(f"Slicing: using first {args.bytes} of {total_available} available bytes.")

    if args.swap:
        print("Byte-swap: enabled (each uint32_t will have its bytes reversed)")

    original_len = len(raw)
    values = bytes_to_uint32_array(raw, swap=args.swap)
    write_c_array(values, args.array_name, args.output, original_len, swap=args.swap)

    print(f"Done: {original_len} bytes → {len(values)} uint32_t values")
    print(f"Output written to: {args.output}")


if __name__ == "__main__":
    main()
